image: ubuntu:22.04

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - common
  script:
    - apt-get update
    - apt-get install -y g++ make cmake
    - apt-get install -y libsfml-dev
    - echo "Compiling the code..."
    - ./run.sh runned
    - echo "Compile complete."

unit-test-job:
  stage: test
  dependencies:
    - build-job
  tags:
    - common
  script:
    - ls
    - cd ./test
    - ./test.sh
  artifacts:
    expire_in: 1 days
    paths:
      - dacha_build/*.png
