image: ubuntu:22.04

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - common
  script:
    - echo "Compiling the code..."
    - ./run.sh runned
    - echo "Compile complete."

unit-test-job:
  stage: test
  tags:
    - common
  script:
    - cd ./test
    - ./test.sh
  artifacts:
    expire_in: 1 days
    paths:
      - dacha_build/*.png
