image: ubuntu:22.04

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - ./run.sh runned
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - cd ./test
    - ./test.sh
